[project]
name = "dungeon-master-bot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pydantic",
    "ollama",
    "pydantic-ai",
    "pypdf>=6.6.0",
    "chromadb>=1.4.1",
]


[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
